### ISSUE TITLE
Pin method for js client.

### ISSUE THREAD

**Issue by AugustoL** [web3-storage/web3.storage#322] opened 2021-08-07 14:56 UTC
It would be super useful to have a pin method, to be used instead of uploading a file, I am interested in just pinning content already uploaded, the only thing I have is the IPFS hash, I think it can be `client.pin(ipfsHash: string || CID)` it can receive an string or CID object.

**Comment by atopal** [comment] 2021-08-10 10:53
duplicate of #289

**Comment by atopal** [comment] 2021-08-10 10:53
Thanks Augusto! Please follow the bug above. Hopefully we can add this soon.

**Closed by atopal** 2021-08-10 10:53 UTC
Labels: kind/enhancement, need/triage
