### ISSUE TITLE
Blocked modal overlay flashes briefly sometimes when browsing web3.storage website

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1998] opened 2022-10-04 18:56 UTC
Sometimes, when clicking through the web3.storage website, a modal pops up for a split second. I've seen this on pretty much all pages of the website, including the docs.

From what I can read in the brief time it's up, I'm pretty sure it's this: https://github.com/web3-storage/web3.storage/blob/main/packages/website/components/account/accountBlockedModal/accountBlockedModal.js

Potentially we are making it appear by default, rather than just making it appear if the account is supposed to be blocked? Also it might not be this exact modal (the word "blocked" is definitely in it), but if it is, we should consider not making it appear on any page except the account page (potentially we call it whenever you're in the logged in state).

**Comment by JeffLowe** [comment] 2022-10-05 17:12
Might be related to a rendering issue we are fixing in #1953 
Just in case, assigning this to @e-schneid

**Comment by e-schneid** [comment] 2022-11-01 16:13
@dchoi27 @JeffLowe I haven't been able to reproduce this and I can't see a scenario in the code where this would happen, but it looks like right now the account blocked modal component will always render in the DOM and we just hide it with CSS.  I'll push up a tiny change to prevent the Account Blocked modal from rendering at all (hidden by CSS or otherwise) unless the user's account is restricted.  This is at least an optimization and perhaps an additional safeguard against the modal displaying when it shouldn't.  @dchoi27, If it continues to display for you after this change please reopen it and I'll do some more investigating.

**Closed** 2022-11-09 21:43 UTC
Labels: kind/bug, pi/dotstorage-site-improvements
