### ISSUE TITLE
Duplicate accounts in web3.storage

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1555] opened 2022-06-22 16:55 UTC
When creating an account with your email address or with a github account linked to that same email, it seems like those accounts are not consolidated and two separate accounts are created.

To be investigated further, but wanted to log that here.

Screenshot of two existing accounts in this situation - have anonymised part of the email address
![image.png](https://images.zenhubusercontent.com/619bc03a70247ff083158a94/bcf54076-ba29-4f56-b7c7-7485541462c4)

**Comment by adamalton** [comment] 2022-06-29 14:59
Yes, this is a known issue. See #1388.

The problem is that there is a single `issuer` column in the `user` table, which can contain *either* the GitHub token, *or* the Magic Link token, but not both together. So if you log in with GitHub and then with Magic Link, you get two separate accounts rather than one.

**Comment by JeffLowe** [comment] 2022-06-29 17:35
Closing this out given root cause in #1388

**Closed by JeffLowe** 2022-06-29 17:35 UTC
Labels: need/triage, potential/websites-pi
