### ISSUE TITLE
small (24K) file fails repeatedly to upload (thousands like it have succeeded) unless I change file extension

### ISSUE THREAD

**Issue by Trott** [web3-storage/web3.storage#323] opened 2021-08-08 21:37 UTC
Using the upload script, I have a single file (among around 12000 files) that fails over and over. Every other file succeeds. Here's the output every time I try to run the getting-started example upload script with it:

```console 
file:///Users/trott/Desktop/Projects/ipfs/node_modules/web3.storage/src/lib.js:155
                throw new Error(res.message)
                      ^

Error: Network connection lost.
    at pRetry.retries (file:///Users/trott/Desktop/Projects/ipfs/node_modules/web3.storage/src/lib.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (/Users/trott/Desktop/Projects/ipfs/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
}
```

I've tried uploading via the web interface too and it also seems to fail, albeit silently.

The file is a text file with `.ocr` extension because it is the output from an OCR process. I have uploaded thousands of similar files so far without a problem, but this one refuses to upload. If I add `.txt` after the `.ocr` extension, the upload works. (See https://bafybeibkozbrqfcbrtvxt5j5ifswz27lvf5u3wscckicd7d7kbjw6rdlry.ipfs.dweb.link/).  I have not had to do this with the other files.

The file in question is available at https://gist.githubusercontent.com/Trott/53d20175e63466777b6c84d7a1468cf7/raw/39c3233ce0085afa354ef726e74d85ab9224b7a4/sfpl_sfh4_009_005.ocr.

**Comment by olizilla** [comment] 2021-08-09 09:43
Thanks for reporting. I'm able to recreate it. Investigating!

**Comment by olizilla** [comment] 2021-08-09 10:34
notes: 

The CID you get when adding sfpl_sfh4_009_005.ocr is bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba
see: https://bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba.ipfs.dweb.link

Using `w3 put` against staging fails in the same way:
```console
$ w3 put ./sfpl_sfh4_009_005.ocr
⁂ using api-staging.web3.storage
# Packed 1 file (0.0MB)
# bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba
⠴ Storingfile:///Users/oli/Code/web3-storage/web3.storage/packages/client/src/lib.js:155
                throw new Error(res.message)
                      ^

Error: Network connection lost.
    at pRetry.retries (file:///Users/oli/Code/web3-storage/web3.storage/packages/client/src/lib.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (/Users/oli/Code/web3-storage/web3.storage/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
```

That CID is reported as Queued against 1 ipfs cluster node, and pinned on 2.
```console
bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba:
    > 12D3KooW...vyzd : REMOTE | 2021-08-09T09:57:18.324313147Z
    > 12D3KooW...ziK6 : REMOTE | 2021-08-09T09:57:18.324313147Z
    > 12D3KooW...Fu3P : REMOTE | 2021-08-09T09:57:18.324313147Z
    > web3-storage-sv15-2  : PINNED | 2021-08-09T09:57:18.39685109Z
    > web3-storage-am6-2   : PIN_QUEUED | 2021-08-09T09:51:31.479891463Z
    > web3-storage-dc13    : PINNED | 2021-08-09T09:57:18.370772959Z
```

The file is smaller than the threshold for doing a `--local` add on ipfs cluster. (24k)

Suspicion: the api call to cluster.add is timing out while cluster attempts to pin the file to 3 nodes, which then exceeds the time budget for our CF worker.

**Comment by olizilla** [comment] 2021-08-09 13:26
The CID is now pinned on 3 cluster nodes, the node that was reporing `PIN_QUEUED` has caugh up. Now figuring out why this prevented the upload from completing, as it should have completed succesfully even when not fully pinned on 3 nodes, or at least thrown a useful error.

**Comment by olizilla** [comment] 2021-08-09 15:19
@hsanjuan what is the expected behaviour of the ipfs-cluster http api when asking it to `add` with a replication factor of 3, `local=false` and `format=car` when 2 nodes have the root CID pinned, and 1 has it as `PIN_QUEUED`? I'm looking in the cluster code, and got as far as the [allocate](https://github.com/ipfs/ipfs-cluster/blob/3ad70a42fc1a5f09b7fc4bfcaaf948eebdcb0612/allocate.go#L50) function to determine if a given block needs to be sent to other nodes, but i'm stuggling to figure out if a node reports `PIN_QUEUED` as the state, does that satisfy the allocator such that it considers the CID replicated across enough nodes? Would the http API then promptly return that the CID was added?

**Comment by hsanjuan** [comment] 2021-08-09 15:52
The /add API should have returned as soon as it finished adding and the cluster peer recorded the pin. That happens regardless on whether that pin operation becomes queued or finished on the local or on other peers.

You say the add may have not returned, so probably one of the receiving peers got stuck on block-put (?).

But it makes no sense that it happens to a very specific file and that it would work with others or just changing the extension, so I'm not sure. The fact that this was pinned before already should not affect things iirc.

**Comment by Trott** [comment] 2021-08-09 16:15
If it's useful to know: I'm still getting the same error when adding the file. (I'm not sure if it's supposed to be cleared up now and this is a post-mortem, or if it's understood to be ongoing.)

**Comment by olizilla** [comment] 2021-08-10 08:43
Thanks! that is useful to know. It works locally now, so something weird is going on.

@Trott can you share the script are you using to upload these files? The script proposed in https://docs.web3.storage/#create-the-upload-script changed recently as the previous version would upload each file seperately rather than all together as a single upload... I'm going to keep investigating what's up with the specific CID you reported, but in the meantime, changing the your upload script may work around the issue. You may also like the `w3` cli https://www.npmjs.com/package/@web3-storage/w3

```sh
$ npm i -g @web3-storage/w3

# set the api token to use
$ w3 token
? Paste your API token for api.web3.storage › 
...

# add a file or directory
$ w3 put path/to/file/or/dir
```

**Comment by olizilla** [comment] 2021-08-10 13:42
Ok, it's probably not cloudflare limits, as the dashboard reports 0 cases of resource exhuastion. However it may well be the js client!

If i use `ipfs-car` to create an equivalent CAR and `curl` it to the api directly, it suceeds!

```console
$ curl -X POST https://api.web3.storage/car --data-binary "@foo.car" -H "Authorization: Bearer ***"
{"cid":"bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba"}
```

**Comment by olizilla** [comment] 2021-08-10 14:21
It is noteable that the _equivalent_ CAR file I created was not identical. I've got ipfs-car@0.4 installed locally and it created a CAR file for `sfpl_sfh4_009_005.ocr` that is `23879` bytes, while the CAR created by the latest version, ipfs-car@0.5.5 is `23838` bytes long (shorter by 41 bytes!)... and the client uses the latest version of ipfs-car. Investigating!

**Comment by olizilla** [comment] 2021-08-10 14:22
yep, `curl`ing the CAR of `sfpl_sfh4_009_005.ocr` created by ipfs-car@0.5.5 directly to the web3.storage api fails in the same way as using the client.

**Comment by hsanjuan** [comment] 2021-08-10 14:51
What is the difference? Does the car contain all the blocks and the root cid header corresponds to the actual root?

**Comment by olizilla** [comment] 2021-08-10 15:07
i'm looking now, but a quick look suggests the CAR created with ipfs-car@0.5 is missing bytes from the end

```diff
+ PERIOD.$103,653.61.pgNbr=15.k.p. #.k.£nzKS?.ÿY* Ñ}jÆ."(©..Gn.=c..A.$.U. â..g{.c$³.ÿ.ÂO.^Øï S%A..KL.ùT....sfpl_sfh4_009_005.ocr.Ð¸.....(.p. Y..9._)a.ô..Ë¹2¾RÅm.Å.keà..9ð.»ï....
- PERIOD.$103,653.61.pgNbr=15.k.p. #.k.£nzKS?.ÿY* Ñ}jÆ."(©..Gn.=c..A.$.U. â..g{.c$³.ÿ.ÂO.^Øï S%A..KL.ùT....sfpl_sfh4_009_005.ocr.Ð¸.....
```

**Comment by hsanjuan** [comment] 2021-08-10 17:48
Would this be an explanation?

1) Partial car uploaded
2) cluster-client waits for it to be pinned in at least 1 place but it never finishes because blocks were not added
3) Time out results in user error

Perhaps when adding the correct CAR file once, blocks are added correctly and adding the "broken" CAR file works from that point.

**Comment by olizilla** [comment] 2021-08-10 22:15
That is a flow we should test, but I don't think that's the problem we're seeing with on this issue, at least not at this point. I've peppered the worker with logs and tested on staging and the problem occurs with the initial POST to cluster

```js
{ "message": ["Adding to cluster"], "level": "log", "timestamp": 1628632697675 },
{ "message": ["cluster client POST https://web3.storage.ipfscluster.io/api/add?cid-version=1&raw-leaves=true&meta-size=23838&local=false&format=car"], "level": "log", "timestamp": 1628632697675 },
{ "message": ["Error: Network connection lost." ], "level": "error", "timestamp": 1628632698197 }
```

but I don't think cluster is the problem. The same code with with same upload works fine in dev mode and locally `curl`ing the CAR file that the client would have generated to the same cluster url with the same params works too

```sh
$ curl 'https://web3.storage.ipfscluster.io/api/add?cid-version=1&raw-leaves=true&meta-size=23838&local=false&format=car' -F "file=@not-ok-ipfs-car-0-5.car" -X POST -H "Authorization: ***"
{"name":"not-ok-ipfs-car-0-5.car","cid":{"/":"bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba"},"bytes":23703}
```

**Comment by hsanjuan** [comment] 2021-08-10 22:44
> https://web3.storage.ipfscluster.io/api/add?cid-version=1&raw-leaves=true&meta-size=23838&local=false&format=car

I am missing `stream-channels=false` in those requests. Didn't we use that option since long ago?

**Comment by olizilla** [comment] 2021-08-10 23:34
not in web3.storage. Looks like that header would only get set if explicitly called for by an options flag, https://github.com/nftstorage/ipfs-cluster/blob/befdbebf657608ca53681e57b37e4110d06c4c1e/index.js#L270-L272 and we're not setting that https://github.com/web3-storage/web3.storage/blob/0216c9deddfdbe5ac5c47bdf85568e6a03b1a507/packages/api/src/car.js#L150-L156

**Comment by olizilla** [comment] 2021-08-10 23:47
Something that smells alot like _bad caching_ is going on in the Cloudflare worker. When uploading this specific file to staging (or prod), the call to cluster client add is calling fetch, and the response object has a status of 200 OK, but the body cannot be parsed.

```console
 wrangler tail --env staging --format pretty
  Connected! Streaming logs from web3-storage-staging... (ctrl-c to quit)
[2021-08-11 00:25:22] [LHR] [Ok] POST https://api-staging.web3.storage/car
 | [Info] Adding to cluster 
 | [Info] cluster client POST https://web3.storage.ipfscluster.io/api/add?cid-version=1&raw-leaves=true&meta-size=23838&local=false&format=car 
 | [Info] cluster add response 7 {"body":{"locked":false},"bodyUsed":false,"headers":{},"ok":true,"redirected":false,"status":200,"statusText":"OK","url":"https://web3.storage.ipfscluster.io/api/add?cid-version=1&raw-leaves=true&meta-size=23838&local=false&format=car","webSocket":null} 
 | [Error] Error: failed to parse cluster response
    at n.add (worker.js:2:38171)
    at async w (worker.js:47:1372)
    at async worker.js:47:4426
    at async Proxy.e.r (worker.js:2:460374) 
```

*but* if i add an additonal junk url search param to the url we use to add to cluster _(`watwat=false` in this case, but anything will do)_, much as one would if trying to cache bust a thing, the response body is parseable, and it all works...

```console
wrangler tail --env staging --format pretty
  Connected! Streaming logs from web3-storage-staging... (ctrl-c to quit)
[2021-08-11 00:26:58] [LHR] [Ok] POST https://api-staging.web3.storage/car
 | [Info] Adding to cluster 
 | [Info] cluster client POST https://web3.storage.ipfscluster.io/api/add?cid-version=1&raw-leaves=true&watwat=false&meta-size=23838&local=false&format=car 
 | [Info] cluster add response 8 {"body":{"locked":false},"bodyUsed":false,"headers":{},"ok":true,"redirected":false,"status":200,"statusText":"OK","url":"https://web3.storage.ipfscluster.io/api/add?cid-version=1&raw-leaves=true&watwat=false&meta-size=23838&local=false&format=car","webSocket":null} 
 | [Info] cluster add response blob {"size":104,"type":"application/json"} 
 | [Info] cluster add response text {"name":"file","cid":{"/":"bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba"},"bytes":23703}
 
 | [Info] cluster add response json {"bytes":23703,"cid":{"/":"bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba"},"name":"file"} 
 | [Info] Checking cluster status of bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba 
 | [Info] pins [{"location":{"peerId":"12D3KooWF6uxxqZf4sXpQEbNE4BfbVJWAKWrFSKamxmWm4E9vyzd","peerName":"12D3KooWF6uxxqZf4sXpQEbNE4BfbVJWAKWrFSKamxmWm4E9vyzd"},"status":"Remote"},{"location":{"peerId":"12D3KooWFe387JFDpgNEVCP5ARut7gRkX7YuJCXMStpkq714ziK6","peerName":"web3-storage-sv15"},"status":"Pinned"},{"location":{"peerId":"12D3KooWHdBjmicdXu5X57mQ65oBpfy4p3ca5p31kfJT9FSUFu3P","peerName":"12D3KooWHdBjmicdXu5X57mQ65oBpfy4p3ca5p31kfJT9FSUFu3P"},"status":"Remote"},{"location":{"peerId":"12D3KooWJeRQfPbiv5U2RqQ9yK3qijbNxKarKEGLMkGrfXJuZ2Bo","peerName":"web3-storage-sv15-2"},"status":"Pinned"},{"location":{"peerId":"12D3KooWLWFUri36dmTkki6o9PwfQNwGb2gsHuKD5FdcwzCXYnwc","peerName":"12D3KooWLWFUri36dmTkki6o9PwfQNwGb2gsHuKD5FdcwzCXYnwc"},"status":"Remote"},{"location":{"peerId":"12D3KooWMbibcXHwkSjgV7VZ8TMfDKi6pZvmi97P83ZwHm9LEsvV","peerName":"web3-storage-dc13"},"status":"Pinned"}] 
 | [Info] Creating upload 
 | [Info] Responding bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba 
```

The other local change to the cluster client wraps the step where we try to `await reponse.json()` in a try catch, and takes the long way around to parsing it to try and figure out what is going on.

**Comment by olizilla** [comment] 2021-08-10 23:51
_what stream-channels=false does, for the curious_
> The stream-channels=false query parameter for the /add endpoint will let the API buffer the output when adding and return a valid JSON array once done, making this API endpoint behave like a regular, non-streaming one. ipfs-cluster-ctl add --no-stream acts similarly, but buffering on the client side. Note that this will cause in-memory buffering of potentially very large responses when the number of added files is very large, but should be perfectly fine for regular usage.
– https://github.com/ipfs/ipfs-cluster/blob/master/CHANGELOG.md#v080---2019-01-16

**Comment by olizilla** [comment] 2021-08-10 23:59
note: adding `stream-channels=false` changes the shape of the add response from an Object to an Array, so the logic in the js cluster client add method needs to be fixed to deal with that. It assumes the add reponse will be an Object.
https://github.com/nftstorage/ipfs-cluster/blob/befdbebf657608ca53681e57b37e4110d06c4c1e/index.js#L55-L56

**Comment by hsanjuan** [comment] 2021-08-11 08:59
> note: adding `stream-channels=false` changes the shape of the add response from an Object to an Array, so the logic in the js cluster client add method needs to be fixed to deal with that. It assumes the add reponse will be an Object.
> https://github.com/nftstorage/ipfs-cluster/blob/befdbebf657608ca53681e57b37e4110d06c4c1e/index.js#L55-L56

Sorry, I realized that since we are uploading CARs, setting stream-channels should not matter in general. However, if an error happens adding and we have not set it to false, the error will only come back in trailing headers (and not as an http error code). This additionally may cut nginx connection because of the "response happening before request body is fully sent"-problem. There might also be a caching problem (something sending bad data), but perhaps you are not getting a good error message because of this.

**Comment by olizilla** [comment] 2021-08-11 11:06
We've got tcpdumps now that show a rogue tcp RST packet from cluster after it sends an OK response when handling the CAR file for this upload. 

It's the filesize / total request size that triggers the issue here rather than a specific CID. We are able to recreate the issue with different CAR files that are the same size. Conversely if there is any change to the total request size; i.e. change the size ot the payload, or keep it the same and change a header, or url query param, and the upload succeeds.

**Comment by alanshaw** [comment] 2021-08-12 16:44
resolved by https://github.com/web3-storage/web3.storage/pull/342

@Trott if you encounter this again please open another issue!...and thanks again for reporting this one.

**Closed by alanshaw** 2021-08-12 16:44 UTC
Labels: kind/bug, effort/days
