### ISSUE TITLE
Interrupted flow when creating multiple tokens on website

### ISSUE THREAD

**Issue by orvn** [web3-storage/web3.storage#1631] opened 2022-07-08 12:31 UTC
Note:  Consider doing at same time as #1608 

## Current behavior

On the tokens page of the website, the user is directed to an input field when they want to create a new token. Creating one, or sometimes two tokens works well, but when attempting to create many tokens, the input field disappears, requiring a page reload before creating more tokens.

## Expected behavior

Ideal behavior is as follows

- After creating one token, the user should be able to click the button again to see a field for new tokens
- The creation of a user's first token should still work the way it currently does (triggers a bounce and focus on the input field)

https://user-images.githubusercontent.com/3689720/177991078-69388ede-6078-496d-8a4f-42c3a59490cc.mp4

**Comment by JeffLowe** [comment] 2022-07-08 14:41
@orvn We're doing work currently in this code as part of the website initiative.  It would be wise for the initiative team to take this one on to prevent conflicting / duplicate work.

**Comment by orvn** [comment] 2022-07-08 14:45
Ah okay, if you'd like to take it over that works @JeffLowe!

**Comment by e-schneid** [comment] 2022-08-19 17:07
@JeffLowe @orvn .  I actually haven't been able to reproduce this.  Are you still seeing the same issue or has this been fixed by other changes?

**Comment by JeffLowe** [comment] 2022-08-19 17:16
I cant get it to replicate either on Chrome latest (MacOS) or Safari (MacOS).

**Comment by e-schneid** [comment] 2022-08-24 17:07
bumping forward to Review/QA since we can't reproduce (you're welcome to close it out but I'm not sure on that process)

**Comment by JeffLowe** [comment] 2022-08-24 20:37
We'll close out for now and watch closely for any reports of the issue occurring again.

**Closed by JeffLowe** 2022-08-24 20:37 UTC
Labels: kind/bug, P1, stack/website, pi/dotstorage-site-improvements
