### ISSUE TITLE
404 page for website

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1212] opened 2022-04-04 21:02 UTC
We need a 404 page for the website! cc @orvn

**Comment by orvn** [comment] 2022-04-05 01:02
@dchoi27 we have one actually! But due to a legacy issue #478 it was redirecting to the home page. This was solved last week in #1172, but I think there hasn't been a new release of Web3.Storage `main` yet.

I'll keep this issue open until it's confirmed that everything works in production though, because this issue might be environment dependent.

Here's what the page looks like now by the way @dchoi27:

![web3-storage-404-screenshhot](https://user-images.githubusercontent.com/3689720/161657744-852a447e-08c3-4ea4-981d-d797af20758d.png)

**Comment by orvn** [comment] 2022-04-08 02:29
Works in production, closing issue

**Closed by orvn** 2022-04-08 02:29 UTC
Labels: kind/bug, stack/website
