### ISSUE TITLE
Replace pin error when passing origin and meta

### ISSUE THREAD

**Issue by GaryHomewood** [web3-storage/web3.storage#925] opened 2022-01-28 14:16 UTC
The pinning service endpoint for replace pin throws an error if origin and meta are passed as part of the request body.

[IPFS Replace pin object spec](https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins~1{requestid}/post)

### Screenshot

![Screenshot 2022-01-28 at 12.01.01 (1).png](https://images.zenhubusercontent.com/6179717ee2ff102416686bc9/6ef6fdaa-2370-4a53-b295-0211ce46fc29)

**Comment by dchoi27** [comment] 2022-01-28 15:24
Duplicate of #926

**Closed by dchoi27** 2022-01-28 15:24 UTC
Labels: kind/bug, need/triage
