### ISSUE TITLE
Using ^ symbol in filename creates new directories when wrapWithDirectory is true in JS Client Library

### ISSUE THREAD

**Issue by karolkudla** [web3-storage/web3.storage#375] opened 2021-08-19 19:10 UTC
Example: 
filename - "foo^bar^^bar^foo.mp4" creates foo/bar/bar/foo.mp4 path when wrapWithDirectory is true.

**Comment by vasco-santos** [comment] 2021-09-03 09:28
Is the double ^ symbol in `"foo^bar^^bar^foo.mp4` a mistake? Or what is it trying to accomplish?

**Comment by olizilla** [comment] 2021-09-03 09:34
@vasco-santos i think the issue is that regardless of double or single `^` in a filename it shouldn't be interpreted as a slash

**Comment by karolkudla** [comment] 2021-09-03 09:35
It was not a mistake
Double ^, triple ^, and more ^ makes one directory, not many.
But in my opinion, these ^ symbols should be simply replaced by something else on API side, to not create a tree of directories.

**Comment by alanshaw** [comment] 2022-04-26 09:31
This was released in https://github.com/ipfs/js-ipfs-unixfs/commit/2a6eff25eae4a4e3b92133f3258d22da5f9f7c1a and ipfs-car currently depends on `^9.0.4` so I think we can consider this resolved.

**Closed by alanshaw** 2022-04-26 09:31 UTC
Labels: kind/bug, P2, effort/quickwin, stack/api-protocols
