### ISSUE TITLE
Pinned folders appear as 'No Name' under managed files

### ISSUE THREAD

**Issue by kimasendorf** [web3-storage/web3.storage#2004] opened 2022-10-05 08:15 UTC
I pinned 54 folders via IPFS desktop yesterday.. and it seems to works great. Mostly, since roughly 85% of the pinned folders appear as 'No Name' under managed files. That is pretty bad, since you cannot see what you have pinned until you open the link.
What can I do to get the names show up correctly?

**Comment by dchoi27** [comment] 2022-10-10 15:38
@mbommerez mind getting someone on the team to chime in here? i'm guessing this might just be how the pinning API is spec'd out but would be great to confirm!

**Comment by mbommerez** [comment] 2022-10-10 15:49
@dchoi27 Will do, i agree with you but will get the team involved.

**Comment by alanshaw** [comment] 2022-10-10 16:06
PSA supports this:
https://ipfs.github.io/pinning-services-api-spec/#operation/addPin

WebUI seems to be sending it https://github.com/ipfs/ipfs-webui/blob/main/src/bundles/pinning.js#L374

Web3.Storage API accepts it when pinning... https://github.com/web3-storage/web3.storage/blob/main/packages/api/src/utils/psa.js#L121

...so might just be a UX problem of displaying the name?...or maybe it's not being sent?

**Comment by flea89** [comment] 2022-10-12 15:46
@kimasendorf as mentioned by Alan, both the API expects the name and IPFS should be sent it across.
I just tried pinning 10 folders to my account and I'm unable to reproduce the issue.

Would you mind giving me some more details to help me reproduce the issue? 
Did you have auto-upload enabled or you did set the pinning to each folder one by one?

Also if you could try again and see it that's still happening for you?

Thanks a lot for the support.

**Comment by kimasendorf** [comment] 2022-10-12 18:04
> @kimasendorf as mentioned by Alan, both the API expects the name and IPFS should be sent it across. I just tried pinning 10 folders to my account and I'm unable to reproduce the issue.
> 
> Would you mind giving me some more details to help me reproduce the issue? Did you have auto-upload enabled or you did set the pinning to each folder one by one?
> 
> Also if you could try again and see it that's still happening for you?
> 
> Thanks a lot for the support.

I really did nothing special. Just pinning via IPFS Desktop. I tried various things. Pinning a folder with html content and a folder of folders.. When I was about to pin 54 folders, the first 10 came up with name and then just no name. Currently still getting no name.. Updated IPFS Desktop to the latest just a few days ago.

**Comment by flea89** [comment] 2022-11-07 13:09
I've done some more testing and I'm pretty confident this is a problem with IPFS desktop rather than the web3.storage.

I've opened an issue [there](https://github.com/ipfs/ipfs-desktop/issues/2327)

**Comment by mbommerez** [comment] 2022-11-28 10:20
This has acknowledged as a ipfs webui issues and can be tracked [here](https://github.com/ipfs/ipfs-webui/issues/2067).

Closing this ticket in the meantime.

**Closed by mbommerez** 2022-11-28 10:20 UTC
Labels: kind/bug, need/triage
