### ISSUE TITLE
User Used Storage  is counting "failed" Uploads

### ISSUE THREAD

**Issue by flea89** [web3-storage/web3.storage#1208] opened 2022-04-04 14:19 UTC
## Description
At the moment `user_used_storage` is counting all the uploads for a user despite some of those uploads might not be successful ( not pinned to the cluster).

## Possible solution
Mimic what we do in the psa pinned content, by selecting only cid that have a pin in the cluster.

**Comment by GaryHomewood** [comment] 2022-04-27 11:07
Duplicate of #1198

**Closed by GaryHomewood** 2022-04-27 11:07 UTC
Labels: kind/bug, need/triage, topic/pot, pi/account-limits
